fix(pomodoro): Improve pomdoro timer sync on new TEs
toggl/toggl-button pull request #1825
Opened 2020-08-28 14:14 UTC by dpsxp

## :star2: What does this PR do?
Improve Pomodoro timer sync when creating TEs on other apps/API. The Pomodoro timer should restart when getting new TEs from other services/API

## :bug: Recommendations for testing
- Turn on Pomodoro 
- I would suggest setting a small interval so you can see the animation better
- Start a new using the extension
- After a few minutes (before the Pomodoro ends) make an API call to start a new running TE.
- The extension should change the running TE to newly created one and set the Pomodoro state based on the current duration of the new TE. 
- If the new TE has a duration already bigger than the Pomodoro interval than the animation should go back to 0% and no alarm should trigger 

#### Sanity check
- Check if Pomodoro still working as expected when only using the extension 
- Updating the duration of TEs should also remove the timer if the new duration is bigger than the interval settings

## :memo: Links to relevant issues or information

close #1801 related #1768

2020-09-14 16:29 UTC, kornelijepetak commented
@dpsxp sorry for taking this long.

I've noticed one thing:
When I run another TE, the TB popup changes to the newly running TE, however, not in the Pomodoro focus mode. It shows as a regular TE (no circle, just timer log).

Is that intentional?

2020-09-15 09:27 UTC, rylek90 requested changes
Can we please rebase it to work with post-rebrand changes? :pray: 

Mostly looks good, I wasn't able to enable focus mode on this branch, though :cry:

2020-09-18 08:42 UTC, dpsxp commented
Focus mode should be back now 👍

2020-09-22 08:50 UTC, rylek90 approved these changes
LGTM 🚀

2020-09-23 14:08 UTC, kornelijepetak approved these changes
Tried. Works. Shipit.

2020-09-23 14:08 UTC, kornelijepetak commented on src/scripts/background.js
> +  triggerPomodoroAlarm: async function (duration) {
Kudos for naming things.

2020-09-28 12:17 UTC, merged