Add $$ for querySelectorAll helper
toggl/toggl-button pull request #1879
Opened 2020-11-09 10:08 UTC by glensc

Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

This adds `$$` global selector do perform `document.querySelectorAll` simlarly to `$` being alias to `document.querySelector`

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information

2020-11-09 10:13 UTC, glensc commented
Maintainers: let me know what you think, I could then replace `document.querySelectorAll` calls to this alias if this is accepted.

Alternative solutions I've considered:
1. modify `$` to always call `querySelectorAll` and change callers to accept first value only. 
2. add the third parameter to `$` function to change the behavior of to use `querySelector` or `querySelectorAll`

Some thoughts of those alternative solutions:
- The "1." alternative may be expensive, the browser may optimize `querySelector` better than doing `querySelectorAll`. 
- The "2." alternative: it's code smell to add another parameter to the function, but it may clean the "global namespace" pristine. I think the global namespace polluting is not an issue as the plugin is run its own document.

2020-12-03 14:08 UTC, glensc commented
ping @rylek90

2020-12-04 13:44 UTC, rylek90 approved these changes
Seems like a nice addition. Thank you for your contribution 🙇 🙌

2020-12-04 13:45 UTC, rylek90 requested changes
Oh, just caught it. Can you, please, fix your commit message to follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) guidelines? 🙏 
You can check history of this repo for some tips

2020-12-06 12:12 UTC, glensc commented
@rylek90 updated according to [CONTRIBUTING.md](https://github.com/toggl/toggl-button/blob/1.67.2/.github/CONTRIBUTING.md)

Also, decided that changing to use the new method, is better to have in separate PR. as it's coverage is higher, and would need more testing than adding new feature.

2020-12-06 13:47 UTC, glensc commented
how do I mark requested changes done?

2020-12-07 15:52 UTC, rylek90 approved these changes
LGTM 🚀

2020-12-07 15:52 UTC, merged