fix(youtrack): Fix task description from agile board (#1797)
toggl/toggl-button pull request #1908
Opened 2021-01-22 12:08 UTC by je-schindler

## :star2: What does this PR do?

This PR fixes the task description when starting a task from youtrack's agile board. Currently the description layout is "A1337 A1337Task name", while it should be just "A1337 Task name".

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox. As mentioned in #1797 it should be tested multiple times, since Toggle Track adds another (pre-PR conflicting) html container.

## :memo: Links to relevant issues or information

#1797

2021-02-05 20:25 UTC, TheSoloJake commented
User [reached](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481306978515) out to Support; @tcrammond wondering if this is something that we may be able to get a quick review and potential merge on?

2021-02-08 09:13 UTC, rylek90 requested changes
Thanks for contribution :raised_hands: 

Code LGTM :rocket: 
Issue seems to be fixed as well

One note, can you fix commit message to contain `Closes #1797` in the last line, so that GH will close the original issue after we merge this?

2021-02-12 23:17 UTC, je-schindler reviewed
--

2021-02-15 10:04 UTC, rylek90 approved these changes
LGTM :rocket:

2021-02-15 10:04 UTC, merged