chore(background): Update websocket url
toggl/toggl-button pull request #1955
Opened 2021-05-11 09:51 UTC by rylek90

## :bug: Recommendations for testing
* Build button
* Log in
* Start time entry in webapp
* See if button fetches it

2021-05-11 09:58 UTC, langri-sha approved these changes
Small req, but otherwise LGTM :+1:

2021-05-12 09:49 UTC, rylek90 commented on src/scripts/background.js
> +      TogglButton.websocket.socket = new WebSocket('wss://track.toggl.com/stream');
Thanks! Done :salute:

2021-05-12 09:53 UTC, langri-sha requested changes

2021-05-12 09:53 UTC, langri-sha commented on src/scripts/background.js
> +      TogglButton.websocket.socket = Object.assign(new URL('/stream', process.env.API_URL), { protocol: 'wss:' }).href;
```suggestion
      TogglButton.websocket.socket = new WebSocket(Object.assign(new URL('/stream', process.env.API_URL), { protocol: 'wss:' }).href);
```

2021-05-12 09:56 UTC, langri-sha approved these changes
Yusss :raised_hands: ! LGTM :rocket:

2021-05-12 10:05 UTC, merged